Part-2 (conversion in numerical and model training)

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('final_data.csv')

In [ ]:
data

Unnamed: 0                                             Tweets         0
0               0                               i come border i kill  Positive
1               1                             im get borderland kill  Positive
2               2                          im come borderland murder  Positive
3               3                         im get borderland 2 murder  Positive
4               4                           im get borderland murder  Positive
...           ...                                                ...       ...
72722       73716  just realiz window partit mac like 6 year behi...  Positive
72723       73717  just realiz mac window partit 6 year behind nv...  Positive
72724       73718  just realiz window partit mac 6 year behind nv...  Positive
72725       73719  just realiz window partit mac like 6 year behi...  Positive
72726       73720  just like window partit mac like 6 year behind...  Positive

[72727 rows x 3 columns]

In [ ]:
data= data.drop(data.columns[0],axis=1)

In [ ]:
data.rename(columns={'0':'sentiments'},inplace=True)

In [ ]:
data['sentiments'].value_counts()

sentiments
Negative      21999
Positive      20286
Neutral       17744
Irrelevant    12698
Name: count, dtype: int64

In [ ]:
data.isna().sum()

Tweets        0
sentiments    0
dtype: int64

In [ ]:
data.dropna(inplace=True,axis=0)

In [ ]:
data.shape

(72727, 2)

In [ ]:
X=data['Tweets']
Y=data['sentiments']

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

vectorizer = CountVectorizer()  
X_counts = vectorizer.fit_transform(X)  

tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit_transform(X_counts) 

In [ ]:
print(X_tfidf)

  (0, 16490)	0.49331992805185615
  (0, 7100)	0.44168332261717896
  (0, 5357)	0.7493672604996569
  (1, 16490)	0.5925659266269032
  (1, 14951)	0.4248653669990299
  (1, 12167)	0.41025133355170057
  (1, 5360)	0.5477671821537234
  (2, 19276)	0.6983753542273423
  (2, 14951)	0.34834903110868304
  (2, 7100)	0.43499302481634494
  (2, 5360)	0.449116783804171
  (3, 19276)	0.7265589113060767
  (3, 14951)	0.3624069653443998
  (3, 12167)	0.34994130463287315
  (3, 5360)	0.4672412901097615
  (4, 19276)	0.7265589113060767
  (4, 14951)	0.3624069653443998
  (4, 12167)	0.34994130463287315
  (4, 5360)	0.4672412901097615
  (5, 31360)	0.26491731676295543
  (5, 30966)	0.2583159429395332
  (5, 26985)	0.1940141385833085
  (5, 26774)	0.1496033057593737
  (5, 26686)	0.267985295827893
  (5, 22255)	0.3018285630347388
  :	:
  (72725, 24093)	0.2750116682168431
  (72725, 21273)	0.4130336053883051
  (72725, 20236)	0.1974819402518872
  (72725, 20111)	0.2859241909411373
  (72725, 17785)	0.32781459469284197
  (72725, 1720

In [ ]:
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB as nb
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,precision_score,recall_score
model=SVC()

In [ ]:
x_vector=pd.DataFrame(X_tfidf)

In [ ]:
vectorizer_data= X_tfidf
target=Y

In [ ]:
X_train,x_test,Y_train,y_test= train_test_split(vectorizer_data,target,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier as ds 
model2= ds()

In [111]:
model2.fit(X_train,Y_train)


DecisionTreeClassifier()

In [112]:
y_pred=model2.predict(x_test)

In [113]:

print("accuracy score :", accuracy_score(y_test,y_pred))
print("f1 score :", f1_score(y_test,y_pred,average="macro"))
print("recall score :", recall_score(y_test,y_pred,average="macro"))
print("precision score :", precision_score(y_test,y_pred,average="macro"))
print("confusion matrix :", confusion_matrix(y_test,y_pred))

accuracy score : 0.7921077959576516
f1 score : 0.7866037621472136
recall score : 0.7841486503961789
precision score : 0.7899140973007953
confusion matrix : [[1815  195  205  315]
 [ 174 3585  274  337]
 [ 153  306 2773  314]
 [ 194  270  287 3349]]


In [114]:

tweet = "fuck you dude"
tweet_vectorized = vectorizer.transform([tweet])
prediction = model2.predict(tweet_vectorized)
print(" Tweet:", tweet)
print("Predicted Sentiment:", prediction[0])


 Tweet: fuck you dude
Predicted Sentiment: Negative


In [115]:
from sklearn.naive_bayes import MultinomialNB

In [116]:
model3= MultinomialNB()
model3.fit(X_train,Y_train)
y_pred=model3.predict(x_test)

print("accuracy score :", accuracy_score(y_test,y_pred))

accuracy score : 0.7054860442733397


In [121]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB


param_grid = {
    'alpha': [0.1, 0.5, 1.0, 2.0],
    'fit_prior': [True,False]
}
clf = MultinomialNB()

grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='accuracy')


grid_search.fit(X_train, Y_train)

best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best parameters:", best_params)
print("Best cross-validation score:", best_score)

Best parameters: {'alpha': 0.1, 'fit_prior': False}
Best cross-validation score: 0.7867688965681914


In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix
import tensorflow as tf

# Assuming X_train, Y_train, x_test, y_test are defined

# Label encoding for Y_train
label_encoder = LabelEncoder()
Y_train_encoded = label_encoder.fit_transform(Y_train)

# One-hot encoding for Y_train if needed (for multi-class classification)
# Y_train_encoded = to_categorical(Y_train_encoded)

# Model creation
model = Sequential()
model.add(LSTM(units=64, input_shape=(X_train.shape[1], X_train.shape[2]), dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Training
model.fit(X_train, Y_train_encoded, epochs=10, batch_size=32, validation_split=0.2)

# Prediction
y_pred = model.predict(x_test)
y_pred_binary = (y_pred > 0.5).astype(int)

# Inverse transform for multi-class classification if one-hot encoding was used
y_pred_labels = label_encoder.inverse_transform(np.argmax(y_pred_binary, axis=1))

# Evaluation
print("accuracy score :", accuracy_score(y_test, y_pred_binary))
print("f1 score :", f1_score(y_test, y_pred_binary, average="macro"))
print("recall score :", recall_score(y_test, y_pred_binary, average="macro"))
print("precision score :", precision_score(y_test, y_pred_binary, average="macro"))
print("confusion matrix :", confusion_matrix(y_test, y_pred_binary))


IndexError: tuple index out of range